from django.urls import path
from .views import (
    welcome,
    CustomLoginView,
    owner_dashboard,
    user_dashboard,
    accept_order,
    delete_order,
    add_menu_item,
    logout_view,
    toggle_availability,
    earnings_report,
    view_cart,
    confirm_order,
    add_to_cart,
    update_cart_item,
    remove_from_cart,
    cancel_order,
    owner_mark_prepared,
    order_confirmed,
    mark_prepared,
    mark_delivered,
    order_confirmation_page
)

urlpatterns = [
    path('', welcome, name='welcome'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('user-dashboard/', user_dashboard, name='user_dashboard'),
    path('owner-dashboard/', owner_dashboard, name='owner_dashboard'),
    path('add-menu-item/', add_menu_item, name='add_menu_item'),
    path('toggle-availability/<int:item_id>/', toggle_availability, name='toggle_availability'),
    path('earnings-report/', earnings_report, name='earnings_report'),
    path('accept-order/<int:order_id>/', accept_order, name='accept_order'),
    path('delete-order/<int:order_id>/', delete_order, name='delete_order'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart-item/<int:cart_item_id>/', update_cart_item, name='update_cart_item'),
    path('view-cart/', view_cart, name='view_cart'),
    path('confirm-order/', confirm_order, name='confirm_order'),
    path('cancel-order/', cancel_order, name='cancel_order'),
    path('order-prepared/<int:order_id>/', owner_mark_prepared, name='mark_order_prepared'),
    path('order/<int:order_id>/mark-prepared/', mark_prepared, name='mark_prepared'),
    path('order/<int:order_id>/mark-delivered/', mark_delivered, name='mark_delivered'),
    path('cart/confirm/<int:order_id>/', order_confirmation_page, name='order_confirmed'),
    path('order-confirmed/', order_confirmed, name='order_confirmed_default'),
]
